return {
  "m4xshen/hardtime.nvim",
  event = "VeryLazy",
  opts = {
    disabled_filetypes = {
      "DressingInput",
      "DressingSelect",
      "TelescopePrompt",
      "checkhealth",
      "dapui-repl",
      "dapui_breakpoints",
      "dapui_console",
      "dapui_scopes",
      "dapui_stacks",
      "dapui_watches",
      "harpoon",
      "help",
      "lazy",
      "mason",
      "neo-tree",
      "neo-tree-popup",
      "neotest-summary",
      "netrw",
      "noice",
      "notify",
      "oil",
      "prompt",
      "qf",
      "undotree",
    },
  },
}
