# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

# Replace the "❯" symbol in the prompt with "➜"
[character] # The name of the module we are configuring is "character"
success_symbol = "[➜](bold green)" # The "success_symbol" segment is being set to "➜" with the color "bold green"

[aws]
# Disable the package module, hiding it from the prompt completely
disabled = true

[directory]
truncation_length = 3
truncation_symbol = "…/"
truncate_to_repo = false

[git_status]
modified = "[](#ff9e3b)"
stashed = ""
staged = '[+\($count\)](green)'
