# theme
import = ["~/.config/alacritty/themes/catppuccin-mocha.toml"]

[window]
decorations = "buttonless"
opacity = 0.84
padding = { x = 2, y = 2 }
option_as_alt = "Both"     # macos only

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
bold_italic = { family = "JetBrainsMono Nerd Font", style = "Bold Italic" }
size = 16.0
offset = { x = 1 }

[keyboard]
# https://github.com/alacritty/alacritty/issues/7608#issuecomment-1975006973
bindings = [{ key = "Slash", mods = "Control", chars = "\u001f" }]
